apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.servername }}
spec:
  hosts:
  - "*"
  http:
  - route:
    - destination:
        host: {{ .Values.virtualService.serverhost }}
        port:
          number: {{ .Values.virtualService.serverport }}