apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
spec:
  selector:
    istio: {{ .Values.gateway.istio }}
  servers:
  - port:
      number: {{ .Values.gateway.port }}
      name: {{ .Values.gateway.portname }}
      protocol: {{ .Values.gateway.protocol }}
    hosts:
    - "*"