apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentvolume.name }}
spec:
  accessModes:
  - {{ .Values.persistentvolume.accessmode }}
  resources:
    requests:
      storage: {{ .Values.persistentvolume.storage }}
  storageClassName: ""