apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentvolume.name }}
spec:
 accessModes:
 - {{ .Values.persistentvolume.accessmode }}
 capacity:
   storage: {{ .Values.persistentvolume.storage }}
 hostPath:
   path: {{ .Values.persistentvolume.path }}